README.md

* Change vimrc link from git to https for correct display

Fix vimrc link

---

README.md
client/src/App.css
client/src/App.js
client/src/results.js
netlify.toml

* We need to deploy front end
* Setup Netlify by netlify.toml

Frontend setup

---

src/students/sample_code.py

fix typo in src/students/sample_code.py

---

src/autograder.py
src/server.py
src/students/sample_task1.py

Private testing data was not tested
* Refactor autograder.py and server.py
* Add private data download from URL set in the environment variables

Private test

---

README.md

I add my understanding of rebase into README. Please check that if this is correct.

[Git-tutorial] Add rebase tutorial in README.md

---

src/students/b04209023.py

Using **urllib** in task 8 is a little tedious. Maybe **requests** would be a better choice when it comes to http requests. 
Definitely helpful. In fact, this is my first time seeing that variable types of arguments in a function can be assigned. 
This is quite interesting overall. Thanks!
<br />  
> - [  ] Did you change the title of this PR to the …

[Needs Review] b04209023 邱迎禎

---

src/students/b07902129.py

[Needs Review]b07902129 何政勳

---

src/students/b04302308.py

use git....
Yes, it provide some knowledge about git and github
<br />  
> - [O ] Did it pass the Flake8 check?
> - [O] Did you test this PR?  
> - [O] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] b04302308 邱黃婷

---

src/students/b07902033.py

push and commit
yes
no
<br />  
> - [Y] Did it pass the Flake8 check?
> - [Y] Did you test this PR?  
> - [Y] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B07902033 陳郁鳳

---

src/students/b07902123.py

Yes
<br />  
> - [ v ] Did it pass the Flake8 check?
> - [ v ] Did you test this PR?  
> - [ v ] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B07902123 蔡奇夆

---

src/students/b07902055.py
src/test_data/task_5_output.txt

How to use git and task 8.
<br />  
> - [ Y ] Did it pass the Flake8 check?
> - [ Y ] Did you test this PR?  
> - [ Y ] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B07902055 謝宗晅

---

src/students/b07902023.py

[Needs Review] B07902023 簡宏曄

---

src/students/b07902067.py

[Needs Review] b07902067 郭宗頴

---

src/students/b07902031.py

[Needs Review] b07902031 黃永雯

---

src/students/b07902047.py

git, github
maybe
too few instructions
<br />  
> - [ O ] Did it pass the Flake8 check?
> - [ O ] Did you test this PR?  
> - [ O ] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] b07902047 羅啟帆

---

src/students/B07902139.py

[Needs Review] B07902139 鄭豫澤

---

src/students/b07902119.py

Everything
A little
Too few instruction
<br />  

[Needs Review] b07902119 熊育霆

---

src/students/b07902117.py

[NeedsReview] B07902117 陳漱宇

---

src/students/b06902137.py

I mistakenly deleted the words in this section, sorry for TAs.

[Needs Review] b06902137徐紹軒

---

src/students/b07902101.py

[Needs Review] B07902101 楊傑森

---

src/students/b07902089.py

The most challenging part in this homework is learning how to  use github especially rebasing. 
Yes,I learned some knowledge about Git and Python
-
<br />  

[Needs Review]b07902089 李智源

---

src/students/b07902021.py

<br />  
> - [ y ] Did it pass the Flake8 check?
> - [ y ] Did you test this PR?  
> - [ y ] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B07902021 簡捷

---

src/students/B07902111.py

[Needs Review] B07902111 張鈰瀚

---

src/students/b07902085.py

[Needs Review] B07902085 張琪

---

src/students/b06209035.py

learn how to use github, some commands are quite confuse. Read the English instruction is a little difficult.
yes, github will be use a lot in the near future. It's better to learn and try earlier.
:))
<br />  
> - [ y ] Did it pass the Flake8 check?
> - [ y] Did you test this PR?  
> - [ y] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review]b06209035 曹習愛

---

src/students/B07902096.py

[Needs Review] B07902096 李佳恩

---

src/students/b06902100.py

environment settings and task 8
yes in learning Python 
no
<br />  
> - [V] Did it pass the Flake8 check?
> - [?] Did you test this PR?  
> - [V] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B06902100

---

src/students/b07902077.py

git
yes
可以多教一點git的使用方法
<br />  
> - [y] Did it pass the Flake8 check?
> - [y] Did you test this PR?  
> - [y] Did you change the title of this PR to the correct format ([status] student_ID)?

[NeedsReview] B07902077 黃嘉宏

---

src/students/b07902133.py

[Needs Review] b07902133 彭道耘

---

src/students/b07902009.py

previous settings
yes
<br />  
> - [Y] Did it pass the Flake8 check?
> - [Y] Did you test this PR?  
> - [Y] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B07902009 尚沂瑾

---

src/students/B07902007.py

[Needs Review]B07902007 伍柏豪

---

src/students/B07902073
src/students/B07902073.py

Using github 
The autograder and flake8 are in different folders. This cause a bit trouble when testing some small changes frequently. 
<br />  
> - [ y ] Did it pass the Flake8 check?
> - [ y ] Did you test this PR?  
> - [ y ] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B07902073 傅子芸

---

src/students/b07902049.py

[NeedsReview] b07902049 謝獻沅

---

src/students/b07902069.py

[Needs Review] B07902069 李哲宇

---

src/students/b07902113.py

[Needs Review] b07902113 陳品鈞

---

src/students/b04202043.py

[Needs Review] b04202043 林亦盛

---

src/students/B07902003.py

[Needs Review]B07902003 吳雲行 

---

src/students/b04505049.py

[Need review]b04505049 黃子昇

---

src/students/B05902135.py

<br />  
> - [ v ] Did it pass the Flake8 check?
> - [ v ] Did you test this PR?  
> - [  v] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] B05902135 曹鼎

---

src/students/B07902037.py

Use ubuntu to code. Trying to get familiar with Vim and Python. 
Yes, I think GitHub and Vim are vital for an engineer.
I stuck in Task 7 for a quiet long time since I don't know that the "Words to say" part should be 
defined by myself, maybe next time you can remind it in the comment. 
<br />  
> - [ Y ] Did it pass the Flake8 check?
> - [ Y ] Did you test this PR?  
> - [ Y ] Did you change the title of this PR to the …

[Needs Review] B07902037 蔡沛勳

---

src/students/r06522601.py

I can't pass task8
Yes
<br />  
> - [ y ] Did it pass the Flake8 check? (except task 8 which I can't pass)
> - [ y ] Did you test this PR?  
> - [ y ] Did you change the title of this PR to the correct format ([status] student_ID)?

[Needs Review] r06522601 蔡誌烜

---

src/students/b05202077.py

[Needs Review]  b05202077 蘇鈺程

---

src/students/B06202007.py

[NeedsReview]B06202007 張睿騰

---

src/students/B07902065.py

[Needs Review] B07902065 楊雨樓

---

src/students/b06902101.py

Image/urllib
Yes, learned much python
Runthrough/suggested tutorials
<br />  

[Needs Review] b06902101

---

src/students/b07902091.py

[Needs Review] b07902091 周俊廷
